# -*- coding: utf-8 -*-
"""basic .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUnhD5FT3ZSG8ARNsVMEW8wWgJw19qLk
"""

# Define the environment
class Environment:
    def __init__(self):
        # Both rooms start dirty
        self.rooms = {'A': 'Dirty', 'B': 'Dirty'}
    def get_room_status(self, room):
        return self.rooms[room]
    def set_room_status(self, room, status):
        self.rooms[room] = status
# Define the agent
class VacuumAgent:
    def __init__(self, environment):
        self.environment = environment
        self.current_location = 'A' # Start in Room A
    def perceive(self):
        # Perceive the current room and its status
        status = self.environment.get_room_status(self.current_location)
        print(f"[Perceive] Agent is in Room {self.current_location} which is {status}")
        return self.current_location, status
    def act(self, location, status):
        # Decide what to do based on rules
        if status == 'Dirty':
            print("[Action] Cleaning the room...")
            self.environment.set_room_status(location, 'Clean')
        else:
            # Move to the other room
            new_location = 'B' if location == 'A' else 'A'
            print(f"[Action] Moving from Room {location} to Room {new_location}")
            self.current_location = new_location
    def run(self, steps=5):
        for step in range(steps):
            print(f"\n--- Step {step + 1} ---")
            location, status = self.perceive()
            self.act(location, status)
# Main Execution
if __name__ == "__main__":
    env = Environment()
    agent = VacuumAgent(env)
    agent.run()

