# -*- coding: utf-8 -*-
"""bml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEHpAG8-3mB_gwXAsPUhEmDZhImbAXa4
"""

# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, accuracy_score
import matplotlib.pyplot as plt
# Step 1: Create a small dataset (historical agent data)
# Features: energy, health, enemy_distance
# Target: action (move, attack, defend)
data = {
"energy": [80, 20, 60, 50, 90, 30, 40, 70, 85, 25],
"health": [90, 30, 70, 40, 95, 20, 35, 75, 80, 25],
"enemy_distance": [5, 20, 10, 15, 3, 25, 18, 7, 4, 22],
"action": ["attack", "defend", "attack", "move", "attack",
"defend", "defend", "attack", "attack", "move"]
}
df = pd.DataFrame(data)
# Step 2: Split into features and labels
X = df[["energy", "health", "enemy_distance"]]
y = df["action"]
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 3: Train Decision Tree
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3, random_state=42)
clf.fit(X_train, y_train)
# Step 4: Predictions
y_pred = clf.predict(X_test)
# Step 5: Evaluate
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))
# Step 6: Visualize Decision Tree
plt.figure(figsize=(8,6))
plot_tree(clf, feature_names=["energy", "health", "enemy_distance"],
class_names=clf.classes_, filled=True, rounded=True)
plt.show()

