# -*- coding: utf-8 -*-
"""chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ol9jwhw6wNfMVuwac3yxCPNLHdjHX-Xi
"""

# AGENT-BASED RULE CHATBOT (Simple AI Agent)
def chatbot_response(user_input):
    """
    A simple rule-based chatbot function that responds
    to user input based on predefined rules.
    """
    user_input = user_input.lower().strip()
    # RULES SECTION
    if "hello" in user_input or "hi" in user_input:
        return "Hello! I’m your friendly AgentBot. How can I assist you today?"
    elif "how are you" in user_input:
        return "I'm doing great! Thanks for asking. How about you?"
    elif "your name" in user_input:
        return "I’m AgentBot — a simple rule-based chatbot created in Python."
    elif "help" in user_input:
        return "Sure! I can answer simple questions, greet you, or have a small chat."
    elif "weather" in user_input:
        return "I can’t access live weather updates now, but it’s always sunny in my world! "
    elif "time" in user_input:
        from datetime import datetime
        current_time = datetime.now().strftime("%H:%M:%S")
        return f"The current time is {current_time}."
    elif "bye" in user_input or "exit" in user_input:
        return "Goodbye! Have a great day ahead!"
    else:
        return "I’m not sure I understand that. Could you please rephrase?"
# MAIN CHAT LOOP
print(" AgentBot: Hello! I’m your chatbot agent. Type 'bye' to exit.\n")
while True:
    user_input = input("You: ")
    # Exit condition
    if user_input.lower() in ["bye", "exit"]:
        print(" AgentBot:", chatbot_response(user_input))
        break
    # Get chatbot response
    response = chatbot_response(user_input)
    print(" AgentBot:", response)

