# -*- coding: utf-8 -*-
"""search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_Uj4JrhQRYbrT7miPqjHKhvVQhk4GkA
"""

from collections import deque
# Environment (Grid World)
# 0 = Free cell, 1 = Obstacle
grid = [
[0, 0, 0, 0, 0],
[0, 1, 1, 1, 0],
[0, 0, 0, 1, 0],
[1, 1, 0, 0, 0],
[0, 0, 0, 1, 0]
]
# Start and goal positions
start = (0, 0) # Top-left corner
goal = (4, 4) # Bottom-right corner
# Possible agent actions: up, down, left, right
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
# Function to check valid move
def is_valid(x, y, visited):
    rows, cols = len(grid), len(grid[0])
    return 0 <= x < rows and 0 <= y < cols and grid[x][y] == 0 and (x, y) not in visited
# AI Agent using BFS
def bfs_pathfinder(start, goal):
    queue = deque()
    queue.append((start, [start])) # (current_position, path_taken)
    visited = set()
    while queue:
        current, path = queue.popleft()
        visited.add(current)
        if current == goal:
            return path
        for dx, dy in actions:
            new_x, new_y = current[0] + dx, current[1] + dy
            if is_valid(new_x, new_y, visited):
                queue.append(((new_x, new_y), path + [(new_x, new_y)]))
    return None # No path found
# Run the agent
path = bfs_pathfinder(start, goal)
# Display the result
if path:
    print("AI Agent Path Found:")
    for step in path:
        print(step)
else:
    print("No path found.")

