# -*- coding: utf-8 -*-
"""sim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CdaZZuKm7MoZr8rRYK8p1ze0Vna2vNQz
"""

import random
import time

# Define the Agent class
class Agent:
    def __init__(self, name, grid_size):
        self.name = name
        self.grid_size = grid_size
        self.position = [random.randint(0, grid_size-1), random.randint(0, grid_size-1)]
        self.partner = None
        self.goal = None

    def set_partner(self, partner):
        self.partner = partner

    def send_message(self, message):
        print(f"{self.name} sends message: {message}")
        self.partner.receive_message(message)

    def receive_message(self, message):
        print(f"{self.name} receives message: {message}")
        if message["type"] == "proposal":
            # Accept the meeting point
            self.goal = message["data"]
            self.send_message({"type": "ack", "data": self.goal})
        elif message["type"] == "ack":
            self.goal = message["data"]

    def propose_meeting_point(self):
        self.goal = [random.randint(0, self.grid_size-1), random.randint(0, self.grid_size-1)]
        self.send_message({"type": "proposal", "data": self.goal})


    def move_towards_goal(self):
        if self.position == self.goal:
            print(f"{self.name} has reached the goal at {self.goal}")
            return True

        for i in range(2):
            if self.position[i] < self.goal[i]:
                self.position[i] += 1
            elif self.position[i] > self.goal[i]:
                self.position[i] -= 1

        print(f"{self.name} moves to {self.position}")
        return False

# Main simulation
def simulate():
    grid_size = 5
    agent_a = Agent("AgentA", grid_size)
    agent_b = Agent("AgentB", grid_size)

    # Connect the agents
    agent_a.set_partner(agent_b)
    agent_b.set_partner(agent_a)

    print(f"Initial Position of AgentA: {agent_a.position}")
    print(f"Initial Position of AgentB: {agent_b.position}\n")

    # AgentA proposes meeting point
    agent_a.propose_meeting_point()

    # Movement loop until both agents meet
    while True:
        a_done = agent_a.move_towards_goal()
        b_done = agent_b.move_towards_goal()
        print("")
        time.sleep(1)
        if a_done and b_done:
            print("✅ Both agents have successfully met at the same location.")
            break

simulate()

