# -*- coding: utf-8 -*-
"""sudoku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqdsjqaX4x6cOHzbmGRauSnxBnz2OHBd
"""

import time
import os

# Define the Sudoku grid (0 = empty cells)
sudoku_grid = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
]

# Function to print the Sudoku board with formatting
def print_board(board):
    os.system('cls' if os.name == 'nt' else 'clear') # Clear screen for visualization
    for i in range(9):
        if i % 3 == 0 and i != 0:
            print("-" * 21)
        for j in range(9):
            if j % 3 == 0 and j != 0:
                print("|", end=" ")
            if board[i][j] == 0:
                print(".", end=" ")
            else:
                print(board[i][j], end=" ")
        print()
    print()

# Function to find the next empty cell
def find_empty(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return i, j # row, col
    return None

# Function to check if placing a number is valid
def is_valid(board, num, pos):
    row, col = pos

    # Check row
    if num in board[row]:
        return False

    # Check column
    if num in [board[i][col] for i in range(9)]:
        return False

    # Check 3x3 subgrid
    box_x = col // 3
    box_y = row // 3
    for i in range(box_y * 3, box_y * 3 + 3):
        for j in range(box_x * 3, box_x * 3 + 3):
            if board[i][j] == num:
                return False

    return True

# Backtracking solver with visualization
def solve(board):
    find = find_empty(board)
    if not find:
        return True # Puzzle solved
    row, col = find

    for num in range(1, 10):
        if is_valid(board, num, (row, col)):
            board[row][col] = num
            print_board(board)
            time.sleep(0.05)

            if solve(board):
                return True

            # Undo and backtrack
            board[row][col] = 0
            print_board(board)
            time.sleep(0.05)

    return False

# Driver code
print("Initial Sudoku Puzzle:")
print_board(sudoku_grid)
input("Press Enter to start solving...")

if solve(sudoku_grid):
    print("Sudoku Solved Successfully!")
    print_board(sudoku_grid)
else:
    print("No solution exists.")

